# Capítulo 5 - Ejercicios

### Ejercicio 1

Basado en el programa `primos.py` y la función `enc_primos.py`, escriba un programa que genere una matriz en la cual se organicen los números primos. Pero en este caso, organícelos en forma de hélice, es decir
```
2x2 matrix
[[ 2.  3.]
 [ 7.  5.]]
3x3 matrix
[[ 17.  19.  23.]
 [ 13.   2.   3.]
 [ 11.   7.   5.]]
4x4 matrix
[[ 17.  19.  23.  29.]
 [ 13.   2.   3.  31.]
 [ 11.   7.   5.  37.]
 [ 53.  47.  43.  41.]]
```
Permita que se pueda crear la matriz de diferentes tamaños (`5x5`, `6x6`, ...).

In [ ]:
import numpy as np
import math as math

In [ ]:
import numpy as np
import math
def primos_vector(maxnum):
  prime = np.zeros(maxnum,dtype=int)
  prime[0]=1  
  for ipos in range (1,maxnum):
    if (prime[ipos]==1):
      continue 
    inum = ipos+1   
    maxj = int(np.floor(maxnum/inum)) 
    for j in range (2,maxj+1):
      imult = j*inum  
      prime[imult-1]=1
  nprime = np.count_nonzero(prime==0)
  pvec = np.zeros(nprime,dtype=int)
  ncnt = 0
  for ipos in range(maxnum):
    if (prime[ipos]==0):
      inum = ipos+1
      pvec[ncnt]=inum
      ncnt = ncnt+1
  return pvec
  

In [ ]:
while True: 
   contp,conti = 0,0
   cant = int(input('Ingresar el número a evaluar para conocer los números primos, (0 para terminar): \n')) 
   if cant ==0:
     print('Fin del programa')
     break  
   dim = int(input('Ingrese la dimensión a, de la matriz axa (un número, por ejemplo a = 2): '))
   primos = primos_vector(cant) 
   if len(primos)<(dim**2):
      print(f'No hay suficientes números primos en el rango para fabricar una matriz {dim}x{dim}')
      continue
   vprimos = primos[0:dim**2]
   mprimos = np.zeros([dim,dim], dtype=int)
   for i in range(1,dim+1):
      if (i%2==0): 
          contp = contp+1
          i_fcd = pospi+contp                                                              #Sea i_fcd el indicador_filas_columnas_a_la_derecha               
          col = vprimos[((i-1)**2):(((i-1)**2)+(i-1))+1]
          mprimos[pospi-conti:i_fcd+1,i_fcd]= col
          fil = np.flip(vprimos[(((i-1)**2)+(i-1)):(((i-1)**2)+(2*(i-1)))+1])              #Que cada número i par se invirtan las filas             
          mprimos[i_fcd, pospi-conti:i_fcd+1]=fil                            
      else: 
          if (i==1):
              pospi = math.ceil(((dim/2)-1))                                                #pospi: posición inicial
              mprimos[pospi,pospi]=2
          else:
              conti = conti+1
              i_fci = pospi-conti                                                           #i_fci:Sea i_fcd el indicador_filas_columnas_a_la_izquierda
              col = np.flip(vprimos[((i**2)-((2*i)-1)):((i**2)-i)+1])                       #Que cada número i impar invierten columnas
              mprimos[pospi-conti:i_fcd+1, i_fci]=col
              fil = vprimos[((i**2)-i):(i**2)]
              mprimos[i_fci, pospi-conti:i_fcd+1]=fil

   print(mprimos,'\n')  


Ingresar el número a evaluar para conocer los números primos, (0 para terminar): 
1000
Ingrese la dimensión a, de la matriz axa (un número, por ejemplo a = 2): 2
[[2 3]
 [7 5]] 

Ingresar el número a evaluar para conocer los números primos, (0 para terminar): 
1000
Ingrese la dimensión a, de la matriz axa (un número, por ejemplo a = 2): 3
[[17 19 23]
 [13  2  3]
 [11  7  5]] 

Ingresar el número a evaluar para conocer los números primos, (0 para terminar): 
1000
Ingrese la dimensión a, de la matriz axa (un número, por ejemplo a = 2): 4
[[17 19 23 29]
 [13  2  3 31]
 [11  7  5 37]
 [53 47 43 41]] 

Ingresar el número a evaluar para conocer los números primos, (0 para terminar): 
1000
Ingrese la dimensión a, de la matriz axa (un número, por ejemplo a = 2): 5
[[73 79 83 89 97]
 [71 17 19 23 29]
 [67 13  2  3 31]
 [61 11  7  5 37]
 [59 53 47 43 41]] 

Ingresar el número a evaluar para conocer los números primos, (0 para terminar): 
1000
Ingrese la dimensión a, de la matriz axa (un número, 

### Ejercicio 2

Un análisis simple de una serie de datos incluye el cálculo del promedio (mean) y la desviación estandard (std). Sin embargo, algunos datos tienen distribuciones estadísticas que no son normales (gaussiana), y una mejor descripción del valor medio de los datos se obtiene con la mediana (median). Para calcular la mediana, se requiere organizar los datos de manera ascendente y así determinar la mediana. Una función que permite reorganizar un arreglo de números utiliza el método de `quicksort`, disponible en mi caso en el módulo.

Cree dos arreglos de 50 y 51 números aleatorios con `numpy` y con funciones determine el promedio, desviación estándar y la mediana del arreglo. No utilice funciones propias de Python para el cálculo. Compare sus resultados con las funciones `np.mean` y `np.median`. 

Puede usar
```
C = np.random.normal(0,1,51)
```
para crear su arreglo. 


In [ ]:
def partition(array, start, end):
    pivot = array[start]
    low = start + 1
    high = end

    while True:
        # Si el valor que estamos buscando es más grande que el pivot
        # No está en el lugar correcto, o sea a la derecha del pivot,
        # Se mueve a la izquierda y se pasa;
        while low <= high and array[high] >= pivot:
            high = high - 1

        # Proceso opuesto al número superior
        while low <= high and array[low] <= pivot:
            low = low + 1
        if low <= high:
            array[low], array[high] = array[high], array[low]
            # Continúa
        else:
          #Si ya se cumplió todo el proceso, fin del loop
            break

    array[start], array[high] = array[high], array[start]

    return high



In [ ]:
def quicksort(array, start, end):
    if start >= end:
        return

    p = partition(array, start, end)
    quicksort(array, start, p-1)
    quicksort(array, p+1, end)

In [ ]:
a1=np.random.normal(0,1,50)
a2=np.random.normal(0,1,51)
print('Leer de izquierda a derecha y de arriba a abajo')
#OJO ----> Quitar los comentarios de los prints por debajo para comparar
print('------------Sin quicksort---------------')
print('a1')
print(a1)
print('a2')
print(a2)
print('------------Con quicksort---------------')
quicksort(a1,0,len(a1)-1)
quicksort(a2,0,len(a2)-1)
print('a1 con quicksort')
print(a1)
print('a2 con quicksort')
print(a2)

Leer de izquierda a derecha y de arriba a abajo
------------Sin quicksort---------------
a1
[ 0.58898963 -0.09347277  0.60719531 -0.47905023 -1.10406337 -0.15136442
 -0.7179722   1.02757873  0.489941    1.45142448 -1.03750184 -1.08840513
  0.82845632  0.93703852  0.28052343 -0.40703504 -0.44524791 -0.15223784
 -0.8202629  -0.99700763 -0.23796233 -0.24811192 -0.75551816  0.40554006
  0.34966627 -1.58828791 -2.09816808  0.46257164  0.88814052 -0.78832859
 -0.10581516  1.24591036  0.30719317 -1.1470996  -1.45379697 -0.37086821
 -1.29710721 -0.77997773 -2.61931301 -2.20543668 -2.3756237  -0.6405606
  2.15553858 -0.54860549 -1.08820186  2.47232394  0.81724053  0.22222586
 -0.39969756 -0.6609061 ]
a2
[-1.03155547  0.56200472 -0.56553698  0.43483419 -0.76165617  0.58176756
  1.10971732 -0.9018876   0.5079006  -0.19251685 -0.9237514  -0.73034969
 -0.26702027 -1.59717212 -0.64966576 -1.01255513 -1.38404957  0.04530453
 -0.71494761  0.59875708 -0.50368912 -1.1483973   0.79041417  0.93908403
 -0.

In [63]:
fmt = '%5.5f'
#PROMEDIO CON NP
def promedio_np(array):
  p = np.mean(array,dtype=float)
  return p
#PROMEDIO CON FUNCIONES:
suma_a1=np.sum(a1)
promedio_a1 = float(suma_a1/(len(a1)))
suma_a2 = np.sum(a2)
promedio_a2 = float(suma_a2/(len(a2)))
print('Con funciones, el promedio de a1 es: ',fmt%(promedio_a1))
print('Con funciones, el promedio de a2 es: ',fmt%(promedio_a2))
print('-------------')
print('Con Numpy, el promedio de a1 es:     ',fmt%(promedio_np(a1)))
print('Con Numpy, el promedio de a2 es:     ',fmt%(promedio_np(a2)))
print('______________________________________________________________')
print('')
#DESVIACIÓN ESTANDAR CON NP:
def desvest_np(array):
  ds_np = np.std(array,axis=None,dtype=float)
  return ds_np
#DESVIACIÓN ESTANDAR CON FUNCIONES:
for i in a1:
  suma_a1 = suma_a1+((i - promedio_a1)**2)
for i in a2:
  suma_a2 = suma_a2+((i - promedio_a2)**2)
def desviacion(array,promedio):
  des = 0 
  for i in array: 
    des = des+((i-promedio)**2)
  des = np.sqrt((des)/(len(array)))
  return des
desv_1=desviacion(a1,promedio_a1)
desv_2=desviacion(a2,promedio_a2)
print('Con funciones, la desviación estándar de a1 es: ',fmt%(desv_1))
print('Con funciones, la desviación estándar de a2 es: ',fmt%(desv_2))
print('-------------')
print('Con Numpy, la desviación estándar de a1 es:     ',fmt%(desvest_np(a1)))
print('Con Numpy, la desviación estándar de a2 es:     ',fmt%(desvest_np(a2)))
print('______________________________________________________________')
#MEDIANA DEL ARREGLO CON NP:
def mediana_np(array):
  m = np.median(array)
  return m
#MEDIANA DEL ARREGLO CON FUNCIONES:
def mediana(array):
    # Se ordena 
    array.sort()
    # Obtener longitud
    longitud = len(array)
    mitad = int(longitud / 2)
    # Si la longitud es par, promediar elementos centrales
    if longitud % 2 == 0:
        mediana = (array[mitad - 1]+array[mitad]) / 2
    else:
        # Si no, es la del centro
        mediana = array[mitad]
    return mediana
print('Con funciones, la mediana de a1 es: ',fmt%(mediana(a1)))
print('Con funciones, la mediana de a2 es: ',fmt%(mediana(a2)))
print('-------------')
print('Con Numpy, la mediana de a1 es:     ',fmt%(mediana_np(a1)))
print('Con Numpy, la mediana de a2 es:     ',fmt%(mediana_np(a2)))
print('______________________________________________________________')

Con funciones, el promedio de a1 es:  -0.26731
Con funciones, el promedio de a2 es:  -0.16793
-------------
Con Numpy, el promedio de a1 es:      -0.26731
Con Numpy, el promedio de a2 es:      -0.16793
______________________________________________________________

Con funciones, la desviación estándar de a1 es:  1.06655
Con funciones, la desviación estándar de a2 es:  1.02239
-------------
Con Numpy, la desviación estándar de a1 es:      1.06655
Con Numpy, la desviación estándar de a2 es:      1.02239
______________________________________________________________
Con funciones, la mediana de a1 es:  -0.38528
Con funciones, la mediana de a2 es:  -0.47867
-------------
Con Numpy, la mediana de a1 es:      -0.38528
Con Numpy, la mediana de a2 es:      -0.47867
______________________________________________________________


### Ejercicio 3

En Geología estructural, tectónica o sismología muchas veces se estudia los esfuerzos y se describen con el tensor de esfuerzos. Suponga que tenemos un tensor de esfuerzos horizontales (solo 2 dimensiones)
$$
\tau = 
\begin{bmatrix}
\tau_{xx} & \tau_{xy}\\
\tau_{yx} & \tau_{yy}\\
\end{bmatrix}
$$

Para un tensor de esfuerzos, siempre es posible encontrar una dirección de tal forma que no haya esfuerzos de cizalla ($\tau_{xy}=\tau_{yx}=0$). Cuando esto se obtiene, se dice que se encontró los ejes principales de esfuerzo. 
$$
\tau^R = 
\begin{bmatrix}
\tau_{1} & 0\\
0 & \tau_{2}\\
\end{bmatrix}
$$

Por convención, los ejes principales están organizados de tal forma que $|\tau_1|>|\tau_2|$.

Escriba un programa que determine que ángulo debe rotar la matriz $\mathbf{\tau}$ 
$$
\tau = \begin{bmatrix}
-27.0 & -7.1\\
-7.1 & -13.0\\
\end{bmatrix} = 
\begin{bmatrix}
\tau_{xx} & \tau_{xy}\\
\tau_{yx} & \tau_{yy}\\
\end{bmatrix}
$$

para obtener (lo más cercano posible) un tensor de esfuerzos con sus ejes principales. Para rotar el tensor un ángulo $\alpha$ debe realizar la operación matricial:
$$
\tau^R = R\tau R^T
$$
donde 
$$
R = 
\begin{bmatrix}
\cos(\alpha) & -\sin(\alpha)\\
\sin(\alpha) & \cos(\alpha)\\
\end{bmatrix}
$$

**Ayuda** Recuerde que debe cambiar el ángulo a radianes para calcular el coseno. Permita que el programa haga la búsqueda del ángulo por Ud., por ejemplo con un `for` loop.

*Nota**: El mismo (y mejor) resultado se puede obtener utilizando algoritmos de algebra lineal, por ejemplo utilizando los *eigenvalues* y *eigenvectors* de la matriz. Pero esto es para más adelante. 


In [ ]:
import math as math
import numpy as np
fm='%2.2f'
#Definición de la matríz Tao:
tao =np.matrix([[-27.0,-7.1],[-7.1,-13.0]])
rango=np.arange(0,90,0.001)
minimo = 1
maximo = 0
for i in rango:
  R =np.matrix([[np.cos(np.radians(i)),(-1*np.sin(np.radians(i)))],[np.sin(np.radians(i)),np.cos(np.radians(i))]])
  R_T = np.transpose(R)
  operacion = R*tao*R_T
  if (abs(operacion[0,1]) < minimo) and abs((operacion[0,1]) > maximo) :
    minimo = operacion[0,1]
    posicion = i
    print('Para el ejercicio dado, según la matriz','\n',tao,'\n','al girar los planos',i,'° se encuentran los planos del esfuerzo')


Para el ejercicio dado, según la matriz 
 [[-27.   -7.1]
 [ -7.1 -13. ]] 
 al girar los planos 67.297 ° se encuentran los planos del esfuerzo


In [ ]:
print('Fin del taller <:°)')

Fin del taller <:°)
