# Capítulo 6 - Ejercicios

### Ejercicio 1

Escriba un programa que lea un archivo de texto plano que contenga 5 números por línea (5 columnas). Calcule el promedio de los 5 números y luego substraiga el promedio a cada una de los 5 números originales. Guarde un nuevo archivo con los valores con el promedio removido (*demeaned*). Permite que el usuario pueda especificar el nombre del archivo de entrada y salida. 

**Nota**: Haga el programa estable, de tal forma que pueda lidiar con cualquier archivo con estas características. 

Por ejemplo, si el archivo de entrada es
```
10 20 30 40 50
1 2 3 4 5
2 4 6 8 10
5 5 5 5 5
```
el programa deberá escribir un nuevo archivo así. 
```
-20.00 -10.00  0.00 10.00 20.00
-2.00 -1.00  0.00  1.00  2.00
-4.00 -2.00  0.00  2.00  4.00
 0.00  0.00  0.00  0.00  0.00
```

In [1]:
#Se ha creado en el bloc de notas un archivo llamato try_data.dat
#Se empieza ahora por cargar el drive:
from google.colab import drive
drive.mount('/content/Mdrive')

Mounted at /content/Mdrive


In [2]:
#Se hace el cambio de directorio:
%cd /content/Mdrive/MyDrive/mgual/Geoinfo/Trabajos/taller5/
! pwd

/content/Mdrive/MyDrive/mgual/Geoinfo/Trabajos/taller5
/content/Mdrive/MyDrive/mgual/Geoinfo/Trabajos/taller5


In [3]:
#Imports:
import numpy as np

In [4]:
# prob_c5_1.py
#Lectura simple del archivo:
import numpy as np
import os
print('El archivo está descrito en formato .dat y corresponde a: ')
fname = 'data/try_data.dat'
f = open(fname,'r')
for line in f:
  print(line)
print('')
print('Ésta será la prueba para poder trabajar con un programa que lea el archivo e imprima lo requerido')
f.close()


El archivo está descrito en formato .dat y corresponde a: 
10.0  20.0  30.0  40.0  50.0

 1.0   2.0   3.0   4.0   5.0

 2.0   4.0   6.0   8.0  10.0

 5.0   5.0   5.0   5.0   5.0

Ésta será la prueba para poder trabajar con un programa que lea el archivo e imprima lo requerido


In [5]:
#Se define primero la función:
import pickle
import os
ruta = os.getcwd()
archivos = os.listdir(ruta)
def promedio (numbers):
  p = (np.sum(numbers))/5
  return p
#Se abre el archivo:
try:
  fname = input("Ingrese el nombre del archivo de 5 columnas en .dat .txt etc... SIN los signos '' :")
  archivo = np.loadtxt(fname) #En mi cado, el fname será: data/try_data.dat
  fout = input("Ingrese el nombre del archivo final para ser guardado en formado .pdf, SIN los signos '': ")
  #En mi caso el fout puede ser data/blank.dat
except:
  print('Lo siento, el archivo no puede ser leído.')
#Se definen las filas a cada vector del archivo importado:
f1 = np.array(archivo[0])
f2 = np.array(archivo[1])
f3 = np.array(archivo[2])
f4 = np.array(archivo[3])
#Promedio de cada fila:
prom1 = promedio(f1)
prom2 = promedio(f2)
prom3 = promedio(f3)
prom4 = promedio(f4)

dato1 = f1 - prom1
dato2 = f2 - prom2
dato3 = f3 - prom3
dato4 = f4 - prom4

Matriz = np.vstack((dato1,dato2,dato3,dato4))
np.savetxt(fout,Matriz,fmt='%2.2f %2.2f %2.2f %2.2f %2.2f')


#ABRIENDO EL TEXTO QUE SE CREÓ EN data/blank.dat:
F = open(fout,'r')
text = F.read()
print(text)
F.close()

Ingrese el nombre del archivo de 5 columnas en .dat .txt etc... SIN los signos '' :data/try_data.dat
Ingrese el nombre del archivo final para ser guardado en formado .pdf, SIN los signos '': data/blank.dat
-20.00 -10.00 0.00 10.00 20.00
-2.00 -1.00 0.00 1.00 2.00
-4.00 -2.00 0.00 2.00 4.00
0.00 0.00 0.00 0.00 0.00



### Ejercicio 2

En Geociencias hay múltiples fuentes para obtener información de todo tipo (geofísica, geología, fallas, geoquímica, etc). Una de ellas se llama GEOROC (\url{http://georoc.mpch-mainz.gwdg.de/georoc/}) que contiene información sobre geoquímica de rocas en el mundo. De ahí se extrajo un archivo llamado `ANDEAN_ARC_1.csv`, que contiene una gran cantidad de información, incluyendo latitud y longitud de muestreo y contenido en peso de $SiO_2$ (entre otras muchas variables).

Utilizando su método preferido (por ejemplo con `pandas` o `numpy`), lea el archivo e imprima los primeros 20 líneas con la Latitud, longitud y porcentaje de $SiO_2$ en peso, que los encuentra en las columnas (4, 6, y 27 respectivamente).  

Tenga también en cuenta que algunas variables tienen valores inexistentes, así que dependiendo del método, debe ajustar dichos casos. 

**Ayuda**: Si usa `pandas`, el `DataFrame` se puede convertir a un arreglo de `numpy` con el comando
```
data = data.to_numpy()
```
Tenga también en cuenta que algunas variables tienen valores inexistentes, así que dependiendo del método, debe ajustar dichos casos. 

**Ayuda 2**: También para extraer la primera columna del `DataFrame`
```
x  = np.array(data.iloc[:,0])
```
**Ayuda 3**: A veces los archivos de texto plano tienen símbolos poco comunes (la ñ por ejemplo) y se debe especificar el `enconding` del archivo. Por ejemplo, pueden usar `encoding = "latin"` en esos casos.  

In [6]:
# prob_c5_2.py

import numpy as np
import pandas as pd
fname = 'data/ANDEAN_ARC_1.csv'
data = pd.read_csv(fname,sep=',', encoding= 'latin',skip_blank_lines=True,low_memory=False)
print('Estructura de pandas')
print(type(data))
print(data) #Se imprime para mostrar que existe el archivo
print('--------------------------------------------------------------------------------------------------------------')
print('')
print('Se imprimen los primeros 20 números de: ')
# Extraer columnas a numpy
latitud = data.iloc[0:20,4].to_numpy()     #columna 4
longitud = data.iloc[0:20,6].to_numpy()    #columna 6
porcentaje = data.iloc[0:20,27].to_numpy() #columna 27
lat = np.array(latitud,dtype=float)
#lat = lat.reshape(4,5)
lon = np.array(longitud,dtype=float)
#lon = lon.reshape(4,5)
por = np.array(porcentaje,dtype=float)
#por = por.reshape(4,5)
print('')
#Loop para mostrar la tabla:
print('            LATITUD            LONGITUD        PORCENTAJE SiO2%')
for i in range(len(lat)):
  print('%19.3f %18.3f %15.3f'%(lat[i],lon[i],por[i]))

Estructura de pandas
<class 'pandas.core.frame.DataFrame'>
                                              CITATIONS  ... UNIQUE_ID
0                                               [19951]  ...   1002540
1                                               [19951]  ...   1002541
2                                               [19951]  ...   1002542
3                                               [19951]  ...   1002543
4                                               [19951]  ...   1002544
...                                                 ...  ...       ...
7720  [20438] GONZALES S. N., GRECO G. A., GONZALES ...  ...       NaN
7721  [20530] SAMANIEGO P., RIVERA M., MARINO J., GU...  ...       NaN
7722  [20531] PALLARES C., QUIDELLEUR X., GILLOT P.-...  ...       NaN
7723  [20547] JONES R. E., KIRSTEIN L. A., KASEMANN ...  ...       NaN
7724  [20550] HOLM P. M., SOAGER N., ALFASTSEN M., B...  ...       NaN

[7725 rows x 171 columns]
--------------------------------------------------------------

### Ejercicio 3

Usando el ejemplo anterior, describa estadísticamente las características de $SiO_2$, $Al_2O_3$, $FeO_{total}$, $CaO$, $MgO$ (columnas 27, 30,34,35,36). Tenga en cuenta que hay valores vacíos, que no deben ser tenidos en cuenta en el cálculo. 


In [7]:
# prob_c5_3.py
import numpy as np
import pandas as pd
fmt = '%2.2f'
fname = 'data/ANDEAN_ARC_1.csv'
data = pd.read_csv(fname, encoding= 'latin',skip_blank_lines=True,low_memory=False)
print('Estructura de pandas')
print(type(data))
print(data) #Se imprime para mostrar que existe el archivo
print('--------------------------------------------------------------------------------------------------------------')
print('')
print('Se imprimen los primeros 20 números de: ')
# Extraer columnas a numpy
SiO2_  = data.iloc[0:20,27].to_numpy()   #columna 27
Al2O3_ = data.iloc[0:20,30].to_numpy()   #columna 30
FeO_t  = data.iloc[0:20,34].to_numpy()   #columna 34
CaO_   = data.iloc[0:20,35].to_numpy()   #columna 35
MgO_   = data.iloc[0:20,36].to_numpy()   #columna 36
#Paso a array:
SiO2  = np.array(SiO2_,dtype=float)
SiO2  = SiO2.reshape(4,5)
Al2O3 = np.array(Al2O3_,dtype=float)
Al2O3 = Al2O3.reshape(4,5)
FeOt  = np.array(FeO_t,dtype=float)
FeOt  = FeOt.reshape(4,5)
CaO   = np.array(CaO_,dtype=float)
CaO   = CaO.reshape(4,5)
MgO   = np.array(MgO_,dtype=float)
MgO   = MgO.reshape(4,5)
print('')

Estructura de pandas
<class 'pandas.core.frame.DataFrame'>
                                              CITATIONS  ... UNIQUE_ID
0                                               [19951]  ...   1002540
1                                               [19951]  ...   1002541
2                                               [19951]  ...   1002542
3                                               [19951]  ...   1002543
4                                               [19951]  ...   1002544
...                                                 ...  ...       ...
7720  [20438] GONZALES S. N., GRECO G. A., GONZALES ...  ...       NaN
7721  [20530] SAMANIEGO P., RIVERA M., MARINO J., GU...  ...       NaN
7722  [20531] PALLARES C., QUIDELLEUR X., GILLOT P.-...  ...       NaN
7723  [20547] JONES R. E., KIRSTEIN L. A., KASEMANN ...  ...       NaN
7724  [20550] HOLM P. M., SOAGER N., ALFASTSEN M., B...  ...       NaN

[7725 rows x 171 columns]
--------------------------------------------------------------

In [8]:
print('Porcentajes  de  Sílice    SiO2 (WT%):','\n',SiO2)
print('Porcentajes  de  Aluminio  SiO2 (WT%):','\n',Al2O3)
print('Porcentajes  de  Hierro    SiO2 (WT%):','\n',FeOt)
print('Porcentajes  de  Calcio    SiO2 (WT%):','\n',CaO)
print('Porcentajes  de  Magnesio  SiO2 (WT%):','\n',MgO,'\n')
print('--------------------------------------------------------------------------------')
print('Se establece ahora que para las muestras, de la número 0 a la número 20')
print('Los porentajes están dados según la suma de los componentes.','\n','     En promedio se tiene que:')
suma_1 = (np.sum(SiO2))/np.size(SiO2)
suma_2 = (np.sum(Al2O3))/np.size(Al2O3)
suma_3 = (np.sum(FeOt))/np.size(FeOt)
suma_4 = (np.sum(CaO))/np.size(CaO)
suma_5 = (np.sum(MgO))/np.size(MgO)
print('Las rocas tienen un valor de',fmt%(suma_1),'% de SiO2')
print('Las rocas tienen un valor de',fmt%(suma_2),'% de Al2O3')
print('Las rocas tienen un valor de',fmt%(suma_3),'% de FeOt')
print('Las rocas tienen un valor de',fmt%(suma_4),'% de CaO')
print('Las rocas tienen un valor de',fmt%(suma_5),'% de MgO')

Porcentajes  de  Sílice    SiO2 (WT%): 
 [[57.22 57.34 57.39 58.9  59.24]
 [59.34 60.83 61.85 61.91 62.3 ]
 [63.04 64.32 64.9  64.96 64.98]
 [65.01 65.1  65.37 66.07 66.21]]
Porcentajes  de  Aluminio  SiO2 (WT%): 
 [[17.37 17.22 17.32 17.56 17.4 ]
 [16.95 17.12 16.69 16.73 16.62]
 [16.52 16.21 16.06 16.11 16.36]
 [15.98 16.07 16.31 16.1  15.9 ]]
Porcentajes  de  Hierro    SiO2 (WT%): 
 [[6.73 6.37 6.24 6.1  5.88]
 [5.75 5.53 5.04 5.1  4.91]
 [4.68 4.   3.98 3.92 4.02]
 [4.14 3.92 3.79 3.59 3.71]]
Porcentajes  de  Calcio    SiO2 (WT%): 
 [[7.47 7.36 7.16 6.79 6.47]
 [6.4  6.06 5.14 5.31 5.05]
 [4.52 3.65 3.76 3.77 3.71]
 [3.62 3.83 3.41 3.19 3.17]]
Porcentajes  de  Magnesio  SiO2 (WT%): 
 [[3.7  3.63 3.58 3.35 3.17]
 [3.09 3.   2.48 2.48 2.4 ]
 [2.26 1.65 1.57 1.62 1.63]
 [1.53 1.57 1.5  1.28 1.29]] 

--------------------------------------------------------------------------------
Se establece ahora que para las muestras, de la número 0 a la número 20
Los porentajes están dados según la

In [9]:
print('Se realiza ahora la sumatoria de los promedios de las 20 muestras de la roca : ')
def suma (a,b,c,d,e):
  s = a+b+c+d+e
  return s
print(fmt%(suma(suma_1,suma_2,suma_3,suma_4,suma_5)),'% es el porcentaje reportado en óxidos de Si,Al,Fe,Ca,Mg')
print('Quiere decir que existe un',fmt%(100-suma(suma_1,suma_2,suma_3,suma_4,suma_5)),'% que corresponde a otros óxidos')
print('Según la tabla dispuesta, las muestras reportan otros datos menores como Mn,Ti,K,Na,P; a ellos se debe el desfase')

Se realiza ahora la sumatoria de los promedios de las 20 muestras de la roca : 
91.15 % es el porcentaje reportado en óxidos de Si,Al,Fe,Ca,Mg
Quiere decir que existe un 8.85 % que corresponde a otros óxidos
Según la tabla dispuesta, las muestras reportan otros datos menores como Mn,Ti,K,Na,P; a ellos se debe el desfase


In [10]:
print('Por las características de los óxidos se presume una roca de composición Andesítica.')

Por las características de los óxidos se presume una roca de composición Andesítica.


In [11]:
print('Fin del taller <:°)')

Fin del taller <:°)
